Blog/urls.py
from django.contrib import admin
from django.urls import path
from blogg import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', views.user_login, name='login'),
    path('signup/', views.user_signup, name='signup'),
    path('logout/', views.user_logout, name='logout'),
    path('addpost/', views.addpost, name='addpost'),
    path('updatepost/<int:id>/', views.updatepost, name='updatepost'),
    path('deletepost/<int:id>/', views.deletepost, name='deletepost'),

]

blogg/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=100)
    desc = models.TextField()

blogg/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.contrib.auth.models import User
from django.utils.translation import gettext, gettext_lazy as _
from .models import Post


class SignUpForm(UserCreationForm):
    password1 = forms.CharField(
        label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(
        label='Confirm Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:

        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        labels = {'first_name': 'First Name',
                  'last_name': 'Last Name', 'email': 'E-Mail'}
        widgets = {'username': forms.TextInput(
            attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(
            attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(
            attrs={'class': 'form-control'}),
            'email': forms.EmailInput(
            attrs={'class': 'form-control'}),

        }


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(
        attrs={'autofocus': True, 'class': 'form-control'}))
    password = forms.CharField(label=_('Password'), strip=False, widget=forms.PasswordInput(
        attrs={'autocomplete': 'current-password', 'class': 'form-control'}))


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'desc']
        labels = {'title': 'Title', 'desc': 'Description'}
        widgets = {'title': forms.TextInput(
            attrs={'class': 'form-control'}), 'desc': forms.Textarea(attrs={'class': 'form-control'}), }

blogg/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import SignUpForm, LoginForm, PostForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .models import Post
from django.contrib.auth.models import Group


def home(request):
    posts = Post.objects.all()
    return render(request, 'blog/home.html', {'posts': posts})

# About page


def about(request):
    return render(request, 'blog/about.html')

# Contact page


def contact(request):
    return render(request, 'blog/contact.html')

# SignUP page


def user_signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            messages.success(
                request, 'Congratulations !! You have become an Author:)')
            user = form.save()
            group = Group.objects.get(name="Author")
            user.groups.add(group)
    else:
        form = SignUpForm()
    return render(request, 'blog/signup.html', {'form': form})

# Login Page


def user_login(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = LoginForm(request=request, data=request.POST)
            if form.is_valid():
                uname = form.cleaned_data['username']
                upass = form.cleaned_data['password']
                user = authenticate(username=uname, password=upass)
                if user is not None:
                    login(request, user)
                    messages.success(request, 'Logged in successfully !!!')
                return HttpResponseRedirect('/dashboard/')
        else:
            form = LoginForm()
        return render(request, 'blog/login.html', {'form': form})
    else:
        return HttpResponseRedirect('/dashboard/ ')

# Dashboard Page


def dashboard(request):
    if request.user.is_authenticated:
        posts = Post.objects.all()
        user = request.user
        full_name = user.get_full_name()
        gps = user.groups.all()
        return render(request, 'blog/dashboard.html', {'posts': posts, 'full_name': full_name, 'groups': gps})
    else:
        return HttpResponseRedirect('/login/')


# Logout


def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')


# Add Post

def addpost(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = PostForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data['title']
                desc = form.cleaned_data['desc']
                pst = Post(title=title, desc=desc)
                pst.save()
                form = PostForm()
        else:
            form = PostForm()

        return render(request, 'blog/addpost.html', {'form': form})

    else:
        return HttpResponseRedirect('/login')


# Update/ Edit Post

def updatepost(request, id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            pi = Post.objects.get(pk=id)
            form = PostForm(request.POST, instance=pi)
            if form.is_valid():
                form.save()
        else:
            pi = Post.objects.get(pk=id)
            form = PostForm(instance=pi)
        return render(request, 'blog/updatepost.html', {'form': form})

    else:
        return HttpResponseRedirect('/login/')

# Delete Post


def deletepost(request, id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            pi = Post.objects.get(pk=id)
            pi.delete()
            return HttpResponseRedirect('/dashboard/')

    else:
        return HttpResponseRedirect('/login')

blogg/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

<div class="col-sm-10">
    <h3 class="text-white my-3">About Page</h3>
    <p>Welcome to the LetsInt. This website is for those who want to write and share their thoughts. The reason behind
        the name of this webiste is 'Interaction'. So it fully sound like 'Let's Interact'. Please write and share your
        thoughts as much as you can because this website is for you people. So start writing your thoughts, we are
        eagerly
        waiting to read them....</p>

    <p>About Admin - Hii my name is Vratant Saxena. I am an Engineer and right now based in Jaipur. I have created this
        website for people's interaction so that people can interact with each other through their thoughts and
        get to understand the thought process of maximum people.</p>

</div>


{% endblock content %}

blogg/templates/blog/addpost.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col sm-10">
    <h3 class="text-white my-3">Dashboard/ Add Post</h3>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Add" class="btn btn-success">
        <a href="{% url 'dashboard' %}" class="btn btn-danger">Cancel</a>
    </form>
</div>
{% endblock content %}

blogg/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/blog/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static '/blog/css/style.css'%}">
    <title>LetsInt</title>
</head>

<body>
    <div class="container-fluid bg-dark">
        {% include 'blog/navbar.html' %}
    </div>

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% block msg %}
                {% endblock msg %}
            </div>
        </div>
        <div class="row">
            {% block side %}
            {% endblock side %}

            {% block content %}
            {% endblock content %}
        </div>
    </div>




    <script src="{% static 'blog/js/jquery.js' %}"></script>
    <script src="{% static 'blog/js/popper.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.js' %}"></script>
</body>

</html>

blogg/templates/blog/contact.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

<div class="col-sm-10">
    <h3 class="text-white my-3">Contact Page</h3>
    <form class="row g-3">
        <div class="col-md-6">
            <label for="inputEmail4" class="form-label">Name</label>
            <input type="email" class="form-control" id="inputEmail4">
        </div>
        <div class="col-md-6">
            <label for="inputPassword4" class="form-label">E-mail</label>
            <input type="password" class="form-control" id="inputPassword4">
        </div>
        <div class="col-12">
            <label for="inputAddress" class="form-label">Message</label>
            <input type="text" class="form-control" id="inputAddress">
        </div>
</div>
<div class="col-40">
    <button type="submit" class="btn btn-primary" class="my-5">Send</button>
</div>
</form>

</div>


{% endblock content %}

blogg/templates/blog/dashboard.html
{% extends 'blog/base.html' %}
{% load static %}

{% block msg %}
{% if message %}
{% for message in messages %}
<div {% if messages.tags %} class="alert alert-{{message.tags}} alert-dismissable fade show" {% endif %}>
    <strong>{{message}}</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>

</div>
{% endfor %}
{% endif %}
{% endblock msg %}


{% block side %}
<div class="col-sm-2 text-white my-5 text-center">
    <h4 class="my-3">Profile</h4>
    <h5>{{full_name}}</h5>
    {% for group in groups %}
    <p>{{group.name}}</p>
    {% endfor %}
</div>
{% endblock side %}



{% block content %}

<div class="col-sm-10">
    <h2 style="text-align: center;" class="text-white my-3">Dashboard Page</h2>
    <a href="{% url 'addpost' %}" class="btn btn-success">Add Post</a>
    <h4 class="text-center alert alert-info mt-3">Show Post Information</h4>
    {% if posts %}
    <table class="table table-hover bg-white">
        <thead>
            <tr class="text-center">
                <th scope="col" style="width:2%">ID</th>
                <th scope="col" style="width:28%">Title</th>
                <th scope="col" style="width:55%">Description</th>
                <th scope="col" style="width:15%">Action</th>

            </tr>
        </thead>
        <tbody>
            {% for post in posts %}
            <tr>
                <th scope="row">{{post.id}}</th>
                <td>{{post.title}}</td>
                <td>{{post.desc}}</td>
                <td class="text-center">
                    <a href="{% url 'updatepost' post.id %}" class="btn btn-warning btn-sm my-3">Edit</a>
                    {% if perms.blog.delete_post %}
                    <form action="{% url 'deletepost' post.id %}" method="post" class="d=inline">{% csrf_token %}
                        <input type="submit" class="btn btn-danger btn-sm" value="Delete">
                    </form>
                    {% endif %}
                </td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h4 class="text-center alert alert-warning">No Records</h4>
    {% endif %}


</div>


{% endblock content %}

blogg/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h2 class="text-white my-3 ">Home Page</h2>
    {% for post in posts %}
    <div class="jumbotron jumbotron-fluid jumbo-color ">
        <div class="container">
            <h1 class="display-4 font-weight-bold">{{post.title}}</h1>
            <p class="lead">{{post.desc}}</p>
        </div>
    </div>
    {% endfor %}

</div>


{% endblock content %}

blogg/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

<div class="col-sm-10">
    <h3 class="text-white my-3">Login Page</h3>



    <form action="" method="post" novalidate>
        {% csrf_token %}
        {% for fm in form %}
        <div class="form-group">
            {{fm.label_tag}} {{fm}} <small class="text-warning">{{ fm.errors|striptags }}</small>
        </div>
        {% endfor %}
        <input type="submit" value="Login" class="btn btn-primary my-3">
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p class="alert alert-danger my-3">{{error}}</p>
        {%endfor %}
        {% endif %}
    </form>
</div>


{% endblock content %}

blogg/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">LetsInt</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about'%}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact' %}">Contact</a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signup' %}">SignUp</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

blogg/templates/blog/signup.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

<div class="col-sm-10">
    <h3 class="text-white my-3">Becoame an Author</h3>
    {% if messages %}
    {% for message in messages %}
    <p {% if message.tags %} class="alert alert-{{message.tags}} mb-5 {% endif %} ">{{message}}</p>
    {% endfor %}
    {% endif %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {% for fm in form %}
        <div class="form-group">
            {{fm.label_tag}} {{fm}} <small class="text-warning">{{ fm.errors|striptags }}</small>
        </div>
        {% endfor %}
        <input type="submit" value="Submit" class="btn btn-primary my-3">
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p class="alert alert-danger my-3 ">{{error}}</p>
        {%endfor %}
        {% endif %}
    </form>


</div>


{% endblock content %}

blogg/templates/blog/updatepost.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col sm-10">
    <h3 class="text-white my-3">Dashboard/ Update Post</h3>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Update" class="btn btn-success">
        <a href="{% url 'dashboard' %}" class="btn btn-danger">Cancel</a>
    </form>
</div>
{% endblock content %}